#!/bin/python3
import importlib.util
import sys
import json
from json import JSONDecodeError
from distutils.file_util import copy_file
import os

# Dynamically load modules we need
# Credits to https://stackoverflow.com/a/67692/6149867
# And for the explanation : http://www.blog.pythonlibrary.org/2016/05/27/python-201-an-intro-to-importlib/
def dynamically_load_module(module, path):
    spec = importlib.util.spec_from_file_location(module, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


#####################################
# Our import for common run file    #
#####################################
sys.path.append("/course/common")

runfile = dynamically_load_module("runfile", "/course/common/runfile.py")

isExist = os.path.exists("./student/Translations")

if not isExist:
  os.makedirs("./student/Translations")

copy_file("/course/common/student/Translations/Translator.java", "./student/Translations/Translator.java")

try:
    task_options = json.load(open('config.json', 'r', encoding="utf-8"))
except JSONDecodeError as e:
    print(_("Impossible de décoder le config.json"))
    print(e)
    exit()

runfile.run(**task_options)