#!/bin/python
#   Copyright (c) 2016 Flitvoye Florian, Dubray Alexandre
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#This script take a .java or .c (or any file wich use exactly the same comment syntax) and remove all the comment.
#The new code is rewrite in the file "name_uncomment.*" where name is the original name of the file and * is the extension of the original file
#The name of the file must be of the forme "path_of_file.extension"
#----START OF THE SCRIPT----#
import sys
#Getting the argument
arg=sys.argv
#Formatting the new filename
arg_split=arg.pop(1).split('.')
name=arg_split.pop(0)
extension="."+arg_split.pop(0)
old_name=name+extension
new_name=name+"_uncomment"+extension
#Reading the file and copying into the new file
data_file_r = open(old_name,'r')
data_file_w = open(new_name,'w')
content=[]
for line in data_file_r:
	content.append(line)
is_in_comment_block=False
#Function that check if the first char which is different of space is *
def isFirstCharStar(str):
	for i in str:
		if i != ' ':
			if i == '*':
				return True
			else:
				return False
#Deleting the comment in the file
for line in content:
	if is_in_comment_block == True:
		if isFirstCharStar(line) == False:
			is_in_comment_block=False		
	else:
		#Lookink for comment of the form //This is a comment
		tmp=line.split('//')
		if len(tmp) == 1: #No comment of this type
			#Looking for comment of the type /* This is a comment */
			tmp=tmp.pop(0)
			tmp= line.split('/*')
			if len(tmp) == 1: #No comment of this type or begining of multiline comment. Copying line in new file
		       		data_file_w.write(line)
			else:
				data_file_w.write(tmp.pop(0))
				tmp=tmp.pop(0)
				tmp = tmp.split('*/')
				if len(tmp) == 1: #On a multiline comment
					is_in_comment_block = True
				else:
					data_file_w.write(tmp.pop(1))
		else:
			data_file_w.write(tmp.pop(0))
	
data_file_r.close()
data_file_w.close()